forge:
  security:
    server:
      excludes:
        - "/actuator/health"
        - "/actuator/health/readiness"
        - "/actuator/health/liveness"
logging:
  level:
    com.sitionix.atmssox.application.usecase: INFO
    com.sitionix.atmssox.application.capability: INFO
